workflows:
  ios-release:
    name: iOS Release
    scripts:
      - name: Install dependencies
        script: |
          set -e
          echo "CM_BUILD_DIR = $CM_BUILD_DIR"
          ls "$CM_BUILD_DIR"
